baseURL = ""
languageCode = "en-us"
title = "Emanuel Claesson"
publishDir = "../public"
theme="soho"

summarylength = 10
enableEmoji = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Software"
    url = "/software"
    weight = 20

  [[menu.main]]
    name = "Hardware"
    url = "/hardware"
    weight = 30

  [[menu.main]]
    name = "Contributions"
    url = "/contributions"
    weight = 40

  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 50

[params]
  author = "Emanuel Claesson"
  description = ""

  profilePicture = "images/profile.jpg"

  copyright = "Emanuel Claesson"
  license = ""
  licenseUrl = ""

  customCss = ["css/soho-eclaesson.css"]

  [[params.socialIcons]]
    icon = "fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/emanuel-claesson-853b911b3/"

  [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/EClaessonlink"

  [taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true # if false, you need to provide you own custom CSS
    style = "fruity"
    tabWidth = 4